
// This file has been generated by the GUI designer. Do not modify.
namespace ParkingPOS
{
	public partial class Boletera
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ParkingPOS.Boletera
			this.Name = "ParkingPOS.Boletera";
			this.Title = global::Mono.Unix.Catalog.GetString ("ParkingPOS - Boletera");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 958;
			this.DefaultHeight = 452;
			this.Show ();
		}
	}
}
